Updated component to support orientation: horizontal/vertical, label position: top/bottom/left/right, step content
KeyValueSoftwareSystems/react-stepper pull request #13
Opened 2023-11-22 06:19 UTC by ReshmaJoshy

- New prop "Orientation" - horizontal / vertical
 - New values for prop "labelPosition" - existing values left and right, new values top and bottom
 - New prop step content
 - Added unit tests (coverage - 100%)
 - Style fixes

2023-11-23 07:08 UTC, arjunrtk-kv approved these changes

2023-11-27 05:56 UTC, bilta-keyvalue requested changes

2023-11-27 06:43 UTC, ReshmaJoshy commented on README.md
> +# React Stepper
Done

2023-11-27 06:55 UTC, bilta-keyvalue approved these changes

2023-11-27 07:05 UTC, merged